kind: role
version: v7
metadata:
  name: demo-access
  description: "Grants SSH access to servers with label 'project: demo'"
spec:
  options:
    max_session_ttl: 8h

  allow:
    logins:
      - develop
      - devops

    node_labels:
      project: "demo"
