kind: role
version: v7
metadata:
  name: corp
  description: "Access to 'prod' servers"
spec:
  options:
    max_session_ttl: 8h
    forward_agent: true

  allow:
    logins:
      - prod

    node_labels:
      server-type: "prod"
